from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch

from datetime import datetime
from reportlab.platypus import Image

from reportlab.lib.enums import TA_LEFT

import os

from reportlab.lib.colors import HexColor

def add_page_number(canvas, doc):

    canvas.saveState()

    width, height = doc.pagesize

    # Header
    canvas.setFillColor(HexColor("#0d6efd"))
    canvas.rect(0, height-35, width, 35, fill=1)

    canvas.setFillColor(HexColor("#FFFFFF"))
    canvas.setFont("Helvetica-Bold", 14)
    canvas.drawString(
        30,
        height-22,
        "PHOTO FORENSICS INVESTIGATION REPORT"
    )

    # Footer
    canvas.setFillColor(HexColor("#666666"))
    canvas.setFont("Helvetica",9)

    canvas.drawString(
        30,
        15,
        "Generated by Photo Forensics Dashboard"
    )

    canvas.drawRightString(
        width-30,
        15,
        f"Page {doc.page}"
    )

    canvas.restoreState()

# =====================================
# Cover Page
# =====================================

def add_cover_page(story, styles, summary):

    title = styles["Title"]
    title.alignment = TA_CENTER

    heading = styles["Heading2"]
    heading.alignment = TA_CENTER

    story.append(Spacer(1,80))

    story.append(

        Paragraph(

            "<font color='#0d6efd'><b>PHOTO FORENSICS</b></font>",

            title

        )

    )

    story.append(

        Paragraph(

            "<b>INVESTIGATION REPORT</b>",

            title

        )

    )

    story.append(Spacer(1,35))

    table = Table(

        [

            ["Report ID", summary["report_id"]],

            ["Overall Risk", summary["risk"]],

            ["Investigation Score", f"{summary['score']}%"],

            ["Confidence", f"{summary['confidence']}%"],

            ["Generated", datetime.now().strftime("%d %B %Y")]

        ],

        colWidths=[2.8*inch,3*inch]

    )

    table.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(0,-1),colors.HexColor("#0d6efd")),

        ("TEXTCOLOR",(0,0),(0,-1),colors.white),

        ("BACKGROUND",(1,0),(1,-1),colors.whitesmoke),

        ("GRID",(0,0),(-1,-1),1,colors.grey),

        ("ALIGN",(0,0),(-1,-1),"CENTER"),

        ("FONTNAME",(0,0),(-1,-1),"Helvetica-Bold"),

        ("BOTTOMPADDING",(0,0),(-1,-1),10)

    ]))

    story.append(table)

    story.append(Spacer(1,60))

    story.append(

        Paragraph(

            "<b>Digital Image Investigation Dashboard</b>",

            heading

        )

    )

    story.append(

        Paragraph(

            "Automatically Generated Investigation Report",

            styles["BodyText"]

        )

    )

    story.append(PageBreak())

# =====================================
# Executive Summary
# =====================================

def add_summary_page(story, styles, summary):

    story.append(

        Paragraph(

            "<b><font color='#0d6efd'>EXECUTIVE SUMMARY</font></b>",

            styles["Title"]

        )

    )

    story.append(Spacer(1,20))

    table = Table(

        [

            ["Overall Risk", summary["risk"]],

            ["Investigation Score", f"{summary['score']}%"],

            ["Confidence", f"{summary['confidence']}%"],

            ["Report ID", summary["report_id"]]

        ],

        colWidths=[2.8*inch,3.2*inch]

    )

    table.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(0,-1),colors.HexColor("#198754")),

        ("TEXTCOLOR",(0,0),(0,-1),colors.white),

        ("BACKGROUND",(1,0),(1,-1),colors.beige),

        ("GRID",(0,0),(-1,-1),1,colors.black),

        ("BOTTOMPADDING",(0,0),(-1,-1),10),

        ("FONTNAME",(0,0),(-1,-1),"Helvetica-Bold")

    ]))

    story.append(table)

    story.append(Spacer(1,30))

    story.append(

        Paragraph(

            "<b>Investigation Findings</b>",

            styles["Heading2"]

        )

    )

    story.append(Spacer(1,10))

    for reason in summary["reasons"]:

        story.append(

            Paragraph(

                "• " + reason,

                styles["BodyText"]

            )

        )

    story.append(PageBreak())

def generate_pdf_report(

    summary,
    image_path,
    file_info,
    metadata,
    gps,
    hashing,
    ela,
    quality,
    histogram,
    noise,
    ai_summary

):

    os.makedirs("static/reports", exist_ok=True)

    filename = (
        "Report_" +
        datetime.now().strftime("%Y%m%d_%H%M%S") +
        ".pdf"
    )

    output_path = os.path.join(
        "static",
        "reports",
        filename
    )

    doc = SimpleDocTemplate(output_path)

    styles = getSampleStyleSheet()

    story = []

    # -----------------------------
    # Cover Page
    # -----------------------------

    add_cover_page(
        story,
        styles,
        summary
    )

    # -----------------------------
    # Executive Summary
    # -----------------------------

    add_summary_page(
        story,
        styles,
        summary
    )

    # -----------------------------
    # Build PDF
    # -----------------------------

    doc.build(
    story,
    onFirstPage=add_page_number,
    onLaterPages=add_page_number
)

    return output_path
